### ISSUE TITLE
Error in cMake step

### ISSUE THREAD

**Issue by vineeshvs** [unosviluppatore/antlr-cpp#1]
Hi,
Thanks for the tutorial. Kindly check the error which I am getting while running _make_
[Error log](https://drive.google.com/open?id=126zRtTLY5WwyOdkFE4o31myWxfg4XAaS)

**Comment by gabriele-tomassetti** [comment]
It seems an error related to a compiler without support for C++11
```#error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.```

We tested on the three major OSes, so it should be a configuration issue. Can you share some info on your platform?

**Comment by vineeshvs** [comment]
Thanks @unosviluppatore 
System settings are as follows:
```
Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
Ubuntu 16.04.6 LTS
Memory: 16GB```

**Comment by gabriele-tomassetti** [comment]
According to [C++ Standards Support in GCC](https://gcc.gnu.org/projects/cxx-status.html#cxx11) you need at least GCC 4.8.1 to have C++11 support. The base version installed on Ubuntu 16.04 is less than that. What is the version you have installed on your system?

As a solution you can try to replace these lines (194-196) in the file CMakeLists.txt:

```
if (APPLE)
  set(CMAKE_CXX_FLAGS "-Wdeprecated -std=c++11" )
endif()
```

with these lines:

```
if (NOT WIN32)
  set(CMAKE_CXX_FLAGS "-Wdeprecated -std=c++11" )
endif()
```

Then you should repeat the `cmake` command.
