### ISSUE TITLE
error after running make

### ISSUE THREAD

**Issue by blob84** [unosviluppatore/antlr-cpp#3]
Hello, this is the error after running make:
`CMakeFiles/antlr4-tutorial.dir/antlr4-runtime/SceneLexer.cpp.o:(.data.rel.ro._ZTV10SceneLexer[_ZTV10SceneLexer]+0x210): undefined reference to "non-virtual thunk to antlr4::Lexer::getSourceName()"`

I am using this gcc version:
`gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 
`

**Comment by gabriele-tomassetti** [comment]
This is probably due to a mismatch between the GCC used to build the antlr-runtime and your code. [Look here for some suggestions in solving the issue](https://github.com/antlr/antlr4/issues/2285).

**Comment by blob84** [comment]
I used the libantlr4-runtime.so.4.7.2 when I installed antlr4 and now it succesfully compile but I get segmentation error after running the executable:
```
enter   name, LT(1)=composition
Segmentation fault

```

**Comment by blob84** [comment]
Ok now it works.
 I used the runtime source from the antlr4 version I've installed.

**Comment by gabriele-tomassetti** [comment]
Glad it was solved.
