### ISSUE TITLE
libantlr4-runtime.dylib, makefile crashes

### ISSUE THREAD

**Issue by havelund** [unosviluppatore/antlr-cpp#4]
The generated make file crashes when copying the dylib.

**Comment by gabriele-tomassetti** [comment]
Sorry, for the late reply.

There have been several different problems with the C++ build, given the many different setups people have. So, we have revamped the organization of the build file. Now, it is based on the CMake script from the ANTLR C++ Runtime, so hopefully it should be more solid. Can you try now if this fixes the issue?

You should read the updated README. This setup will directly download the ANTLR C++ runtime from the official github repository, so the build will require a bit of patience the first time.

**Comment by havelund** [comment]
Cool!!

Can you point to the README file you refer to?

klaus

**Comment by havelund** [comment]
I can imagine it is a nightmare to maintain this kind of documentation.

Klaus

**Comment by gabriele-tomassetti** [comment]
There is a README for this project in the main directory: https://github.com/gabriele-tomassetti/antlr-cpp/blob/master/README.md . This is the one you want, if you want to build this project.

There is also a readme inside the cmake directory https://github.com/gabriele-tomassetti/antlr-cpp/blob/master/cmake/README.md
which comes from the official ANTLR project. This is the one you want, if you want to learn how to build your own ANTLR projects.

> I can imagine it is a nightmare to maintain this kind of documentation.

Well, in my experience it is always a nightmare to maintain a cross-platform C++ project. The documentation is just the icing on the cake. The consolation is that we have to keep updated for work, so at least this way we help other people.

**Comment by havelund** [comment]
Many thanks, I will keep you updated how it goes.

Klaus
