### ISSUE TITLE
error: conversion from ‘antlrcpp::Any’ to non-scalar type ‘Scene’ requested

### ISSUE THREAD

**Issue by aherlihy** [unosviluppatore/antlr-cpp#6]
Hi, I've just built the repo from a clean clone and I am getting a compilation error in antlr.cpp. `Cmake ..` completes without issue but upon calling `make` I get the following error:

```
/usr/bin/c++  -DANTLR4CPP_STATIC -I/home/dev/antlr-cpp/build/antlr4_runtime/src/antlr4_runtime/runtime/Cpp/runtime/src -I/usr/include/OpenEXR -I/usr/include/x86_64-linux-gnu/ImageMagick-6 -I/usr/include/ImageMagick-6 -I/home/dev/antlr-cpp -I/home/dev/antlr-cpp/libs -isystem /usr/include/opencv4  -Wdeprecated -Wno-attributes   -std=gnu++11 -o CMakeFiles/antlr4-tutorial.dir/antlr.cpp.o -c /home/dev/antlr-cpp/antlr.cpp
/home/dev/antlr-cpp/antlr.cpp: In function ‘int main(int, const char**)’:
/home/dev/antlr-cpp/antlr.cpp:23:36: error: conversion from ‘antlrcpp::Any’ to non-scalar type ‘Scene’ requested
   23 |     Scene scene = visitor.visitFile(tree);
      |                   ~~~~~~~~~~~~~~~~~^~~~~~
make[2]: *** [CMakeFiles/antlr4-tutorial.dir/build.make:97: CMakeFiles/antlr4-tutorial.dir/antlr.cpp.o] Error 1
make[2]: Leaving directory '/home/dev/antlr-cpp/build'
make[1]: *** [CMakeFiles/Makefile2:82: CMakeFiles/antlr4-tutorial.dir/all] Error 2
make[1]: Leaving directory '/home/dev/antlr-cpp/build'
make: *** [Makefile:87: all] Error 2
```

I'm using cmake 3.16.3, on ubuntu 20.04.2, and /usr/bin/c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0. Please let me know if I'm doing something wrong or if there's some versioning issue? I have only the ANTLR installed by cmake which is 4.9.1.

Thank you very much for the very helpful tutorial :)

**Comment by gabriele-tomassetti** [comment]
You are not doing anything wrong. I have verified that, on a similar setup, it did not work on my machine either. I guess there were updates to the compiler configuration that make it stricter. I did update the code to fix the issue.

Can you confirm that now it works for you, too?

Thanks for raising this issue.
