### ISSUE TITLE
Makefile unable to write generated src

### ISSUE THREAD

**Issue by Seniatical** [unosviluppatore/antlr-cpp#9]
CMake runs perfectly fine, its just when I run `make` that it doesn't want to write the files

![image](https://github.com/gabriele-tomassetti/antlr-cpp/assets/69202104/5eb021a1-6fad-4764-b582-a75e62d5ed54)

**Comment by gabriele-tomassetti** [comment]
Are you using WSL (Windows Subsystem for Linux)? If so, did you perform some of the steps in Windows? Sometimes this can mess up things. Try also changing permissions for files.
Where fcssLexer come from? I do not recognize it from the tutorial.

**Comment by Seniatical** [comment]
managed to fix it was just a permissions problem like you mentioned
